version: 2
updates:
  # PHP / Laravel bağımlılıkları
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  # Node.js / Vue bağımlılıkları
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
